### ISSUE TITLE
Inconsistent open depths

### ISSUE THREAD

**Issue by schostac** [OrkhanAlikhanov/prosemirror-replaceattrs#4]
When I call `tr.replaceAttrs(1, attrs)`, it throws `Inconsistent open depths from prosemirror's `replace` code here:

```
if ($from.depth - slice.openStart != $to.depth - slice.openEnd)
    { throw new ReplaceError("Inconsistent open depths") }
```
1 is the correct position because the node I want to update is always at that position.

**Comment by OrkhanAlikhanov** [comment]
Hey! Show your document json as well

**Comment by schostac** [comment]
Hi, sure.

`{ "type": "doc", "content": [ { "type": "root", "attrs": { "left": 100, "right": 100, "top": 100, "bottom": 100 }, "content": [ { "type": "paragraph", "content": [ { "type": "text", "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries." } ] }, { "type": "paragraph", "content": [ { "type": "text", "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries." } ] } ] } ] }`

What I want is to change the attributes of that root node, which roughly looks like this (note that I'm using Tiptap2 + Vue3):
```
export default Node.create({
  name: 'root',
  group: 'block',
  content: 'block+',

  addAttributes() {
    return {
      left: {
        default: 100,
      },
      right: {
        default: 100,
      },
      top: {
        default: 100,
      },
      bottom: {
        default: 100,
      }
    }
  },

 ...

  addNodeView() {
    return VueNodeViewRenderer(Root)
  }
})
```

**Comment by schostac** [comment]
Hi @OrkhanAlikhanov , I've sent [this](https://github.com/OrkhanAlikhanov/prosemirror-replaceattrs/pull/5) pull request to suggest some changes that work my use cases (see more in the added test). Please have a look.
